name: Keep Alive Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes
  workflow_dispatch:

jobs:
  trigger-private-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger private repo workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PRIVATE_REPO_TOKEN }}" \
          https://api.github.com/repos/<jeremyberard01>/<algo>/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'
